=== LachlanB96/WSDAssignment/web/WEB-INF/flights.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="http://www.uts.edu.au/31284/wsd-ass"
    xmlns="http://www.uts.edu.au/31284/wsd-ass"
    elementFormDefault="qualified">
    
    
    <xs:simpleType name="dateFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}-[0-1]{1}[0-9]{1}-[0-3]{1}[0-9]{1}"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="priceFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]+\.[0-9][0-9]"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="numofSeatsFormat">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="cityFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="Sydney|Melbourne|Brisbane|Canberra|Hobart|Adelaide|Darwin|Perth"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="flightTypeFormat">
        <xs:restriction base="xs:string">
            <xs:pattern value="Business|Economy"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="IDFormat">
        <xs:restriction base="xs:integer">
            <xs:pattern value="\d{4}"/>
        </xs:restriction>
    </xs:simpleType>
  
    
    <xs:element name="flights">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="flight" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="departureDate" type="dateFormat"/>
                            <xs:element name="price" type="priceFormat"/>
                            <xs:element name="numofSeats" type="numofSeatsFormat"/>
                            <xs:element name="origin" type="cityFormat"/>
                            <xs:element name="destination" type="cityFormat"/>
                            <xs:element name="flightType" type="flightTypeFormat"/>
                            <xs:element name="description" type="xs:string"/>
                            <xs:element name="flightID" type="IDFormat"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== LachlanB96/WSDAssignment/web/WEB-INF/flights.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<flights xmlns="http://www.uts.edu.au/31284/wsd-ass"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://www.uts.edu.au/31284/wsd-ass flights.xsd">
    <flight>
        <departureDate>30-05-2017</departureDate>
        <returnDate>03-06-2017</returnDate>
        <price>70.00</price>
        <numofSeats>9</numofSeats>
        <origin>Sydney</origin>
        <destination>Melbourne</destination>
        <flightType>Business</flightType>
        <flightID>1001</flightID>
    </flight>
    <flight>
        <departureDate>30-05-2017</departureDate>
        <returnDate>03-06-2017</returnDate>
        <price>70.00</price>
        <numofSeats>7</numofSeats>
        <origin>Sydney</origin>
        <destination>Brisbane</destination>
        <flightType>Business</flightType>
        <flightID>1002</flightID>
    </flight>
    <flight>
        <departureDate>08-07-2017</departureDate>
        <returnDate>11-07-2017</returnDate>
        <price>70.00</price>
        <numofSeats>3</numofSeats>
        <origin>Melbourne</origin>
        <destination>Sydney</destination>
        <flightType>Business</flightType>
        <flightID>1003</flightID>
    </flight>
    <flight>
        <departureDate>09-07-2017</departureDate>
        <returnDate>15-07-2017</returnDate>
        <price>70.00</price>
        <numofSeats>8</numofSeats>
        <origin>Melbourne</origin>
        <destination>Brisbane</destination>
        <flightType>Business</flightType>
        <flightID>1004</flightID>
    </flight>
    <flight>
        <departureDate>22-06-2017</departureDate>
        <returnDate>25-06-2017</returnDate>
        <price>70.00</price>
        <numofSeats>0</numofSeats>
        <origin>Brisbane</origin>
        <destination>Sydney</destination>
        <flightType>Business</flightType>
        <flightID>1005</flightID>
    </flight>
    <flight>
        <departureDate>13-06-2017</departureDate>
        <returnDate>18-06-2017</returnDate>
        <price>70.00</price>
        <numofSeats>3</numofSeats>
        <origin>Brisbane</origin>
        <destination>Melbourne</destination>
        <flightType>Business</flightType>
        <flightID>1006</flightID>
    </flight>
    <flight>
        <departureDate>30-05-2017</departureDate>
        <returnDate>03-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>2</numofSeats>
        <origin>Sydney</origin>
        <destination>Melbourne</destination>
        <flightType>Economy</flightType>
        <flightID>2001</flightID>
    </flight>
    <flight>
        <departureDate>30-05-2017</departureDate>
        <returnDate>03-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>6</numofSeats>
        <origin>Sydney</origin>
        <destination>Brisbane</destination>
        <flightType>Economy</flightType>
        <flightID>2002</flightID>
    </flight>
    <flight>
        <departureDate>01-08-2017</departureDate>
        <returnDate>06-08-2017</returnDate>
        <price>30.00</price>
        <numofSeats>12</numofSeats>
        <origin>Sydney</origin>
        <destination>Hobart</destination>
        <flightType>Economy</flightType>
        <flightID>2003</flightID>
    </flight>
    <flight>
        <departureDate>20-07-2017</departureDate>
        <returnDate>03-08-2017</returnDate>
        <price>80.00</price>
        <numofSeats>19</numofSeats>
        <origin>Sydney</origin>
        <destination>Darwin</destination>
        <flightType>Economy</flightType>
        <flightID>2004</flightID>
    </flight>
    <flight>
        <departureDate>07-07-2017</departureDate>
        <returnDate>18-07-2017</returnDate>
        <price>90.00</price>
        <numofSeats>9</numofSeats>
        <origin>Sydney</origin>
        <destination>Perth</destination>
        <flightType>Economy</flightType>
        <flightID>2005</flightID>
    </flight>
    <flight>
        <departureDate>20-06-2017</departureDate>
        <returnDate>27-06-2017</returnDate>
        <price>70.00</price>
        <numofSeats>3</numofSeats>
        <origin>Sydney</origin>
        <destination>Adelaide</destination>
        <flightType>Economy</flightType>
        <flightID>2006</flightID>
    </flight>
    <flight>
        <departureDate>08-06-2017</departureDate>
        <returnDate>17-06-2017</returnDate>
        <price>50.00</price>
        <numofSeats>2</numofSeats>
        <origin>Sydney</origin>
        <destination>Canberra</destination>
        <flightType>Economy</flightType>
        <flightID>2007</flightID>
    </flight>
    <flight>
        <departureDate>31-05-2017</departureDate>
        <returnDate>04-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>0</numofSeats>
        <origin>Melbourne</origin>
        <destination>Sydney</destination>
        <flightType>Economy</flightType>
        <flightID>3001</flightID>
    </flight>
    <flight>
        <departureDate>03-06-2017</departureDate>
        <returnDate>09-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>0</numofSeats>
        <origin>Melbourne</origin>
        <destination>Brisbane</destination>
        <flightType>Economy</flightType>
        <flightID>3002</flightID>
    </flight>
    <flight>
        <departureDate>07-06-2017</departureDate>
        <returnDate>12-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>2</numofSeats>
        <origin>Melbourne</origin>
        <destination>Canberra</destination>
        <flightType>Economy</flightType>
        <flightID>3003</flightID>
    </flight>
    <flight>
        <departureDate>17-06-2017</departureDate>
        <returnDate>22-06-2017</returnDate>
        <price>60.00</price>
        <numofSeats>10</numofSeats>
        <origin>Melbourne</origin>
        <destination>Hobart</destination>
        <flightType>Economy</flightType>
        <flightID>3004</flightID>
    </flight>
    <flight>
        <departureDate>17-06-2017</departureDate>
        <returnDate>22-06-2017</returnDate>
        <price>50.00</price>
        <numofSeats>7</numofSeats>
        <origin>Melbourne</origin>
        <destination>Adelaide</destination>
        <flightType>Economy</flightType>
        <flightID>3005</flightID>
    </flight>
    <flight>
        <departureDate>17-06-2017</departureDate>
        <returnDate>21-06-2017</returnDate>
        <price>60.00</price>
        <numofSeats>10</numofSeats>
        <origin>Melbourne</origin>
        <destination>Darwin</destination>
        <flightType>Economy</flightType>
        <flightID>3006</flightID>
    </flight>
    <flight>
        <departureDate>07-06-2017</departureDate>
        <returnDate>22-06-2017</returnDate>
        <price>80.00</price>
        <numofSeats>10</numofSeats>
        <origin>Melbourne</origin>
        <destination>Perth</destination>
        <flightType>Economy</flightType>
        <flightID>3007</flightID>
    </flight>
    <flight>
        <departureDate>17-06-2017</departureDate>
        <returnDate>22-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>10</numofSeats>
        <origin>Brisbane</origin>
        <destination>Sydney</destination>
        <flightType>Economy</flightType>
        <flightID>4001</flightID>
    </flight>
    <flight>
        <departureDate>17-06-2017</departureDate>
        <returnDate>22-06-2017</returnDate>
        <price>30.00</price>
        <numofSeats>3</numofSeats>
        <origin>Brisbane</origin>
        <destination>Melbourne</destination>
        <flightType>Economy</flightType>
        <flightID>4002</flightID>
    </flight>
    <flight>
        <departureDate>13-06-2017</departureDate>
        <returnDate>20-06-2017</returnDate>
        <price>50.00</price>
        <numofSeats>13</numofSeats>
        <origin>Brisbane</origin>
        <destination>Canberra</destination>
        <flightType>Economy</flightType>
        <flightID>4003</flightID>
    </flight>
    <flight>
        <departureDate>27-06-2017</departureDate>
        <returnDate>30-06-2017</returnDate>
        <price>60.00</price>
        <numofSeats>10</numofSeats>
        <origin>Brisbane</origin>
        <destination>Hobart</destination>
        <flightType>Economy</flightType>
        <flightID>4004</flightID>
    </flight>
    <flight>
        <departureDate>27-06-2017</departureDate>
        <returnDate>30-06-2017</returnDate>
        <price>60.00</price>
        <numofSeats>10</numofSeats>
        <origin>Brisbane</origin>
        <destination>Adelaide</destination>
        <flightType>Economy</flightType>
        <flightID>4005</flightID>
    </flight>
    <flight>
        <departureDate>27-06-2017</departureDate>
        <returnDate>30-06-2017</returnDate>
        <price>60.00</price>
        <numofSeats>0</numofSeats>
        <origin>Brisbane</origin>
        <destination>Darwin</destination>
        <flightType>Economy</flightType>
        <flightID>4006</flightID>
    </flight>
    <flight>
        <departureDate>27-06-2017</departureDate>
        <returnDate>30-06-2017</returnDate>
        <price>60.00</price>
        <numofSeats>10</numofSeats>
        <origin>Brisbane</origin>
        <destination>Perth</destination>
        <flightType>Economy</flightType>
        <flightID>4007</flightID>
    </flight>
    <flight>
        <departureDate>27-06-2017</departureDate>
        <returnDate>30-06-2017</returnDate>
        <price>50.00</price>
        <numofSeats>10</numofSeats>
        <origin>Canberra</origin>
        <destination>Sydney</destination>
        <flightType>Economy</flightType>
        <flightID>5001</flightID>
    </flight>
    <flight>
        <departureDate>27-06-2017</departureDate>
        <returnDate>30-06-2017</returnDate>
        <price>50.00</price>
